import { Task } from "../types/taskTypes";

export const dummyTasks: Task[] = [
  {
    id: "123",
    title: "Cleaning",
    from: "Kitchen",
    to: "Dining Room",
    assignee:"Rajesh",
    taskType: "internal",
    status: "completed",
    isRecurring: true,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    completionStatus: "onTime",
    hasComplaint: false,
    rating: 5,
  },
  {
    id: "128",
    title: "Cleaning",
    from: "Kitchen",
    to: "Dining Room",
    assignee:"Suresh",
    taskType: "internal",
    status: "ongoing",
    isRecurring: true,
    scheduledDate: new Date(Date.now() + 20 * 60000),
    acceptanceStatus: "notAccepted",
    completionStatus: "onTime",
    hasComplaint: false,
    rating: 5,
  },
  {
    id: "122376",
    title: "Cleaning",
    from: "Room 12",
    to: "Reception",
    assignee:"James",
    taskType: "internal",
    status: "ongoing",
    isRecurring: true,
    scheduledDate: new Date(Date.now() + 20 * 360000),
    acceptanceStatus: "notAccepted",
    completionStatus: "onTime",
    hasComplaint: false,
    rating: 5,
  },
  {
    id: "456",
    title: "Stocking",
    from: "Warehouse",
    to: "Store",
    assignee:"Rajesh",
    taskType: "internal",
    status: "completed",
    isRecurring: false,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    completionStatus: "onTime",
    hasComplaint: false,
    rating: 4,
    reqCategory: "itemRequest",
    items: [
      { itemName: "Boxes", quantities: 10 },
      { itemName: "Packets", quantities: 20, description: "Handle with care" },
    ],
  },
  {
    id: "789",
    title: "Repair",
    from: "Room 101",
    to: "Maintenance",
    assignee:"Sunita",
    taskType: "internal",
    status: "completed",
    isRecurring: true,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    completionStatus: "onTime",
    hasComplaint: true,
    rating: 3,
    reqCategory: "serviceRequest",
    services: [
      { serviceName: "Plumbing" },
      { serviceName: "Electrical", description: "Emergency" },
    ],
  },
  {
    id: "790",
    title: "Repair",
    from: "Room 101",
    to: "Maintenance",
    assignee:"Sanju",
    taskType: "internal",
    status: "scheduled",
    isRecurring: true,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    rating: 3,
    reqCategory: "serviceRequest",
    services: [
      { serviceName: "Plumbing" },
      { serviceName: "Electrical", description: "Emergency" },
    ],
  },
  {
    id: "101112",
    title: "Maintenance",
    from: "Facilities",
    to: "Rooms",
    assignee:"Ramesh",
    taskType: "internal",
    status: "completed",
    isRecurring: false,
    scheduledDate: new Date(),
    completionStatus: "delayed",
    hasComplaint: false,
    rating: 2,
  },
  {
    id: "131415",
    title: "Checkup",
    from: "Lab",
    to: "Clinic",
    assignee:"Rohan",
    taskType: "internal",
    status: "completed",
    isRecurring: true,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    completionStatus: "onTime",
    hasComplaint: true,
    rating: 1,
  },
  {
    id: "161718",
    title: "Guest Services",
    from: "Reception",
    to: "Room 201",
    assignee:"Ian",
    taskType: "guest",
    status: "completed",
    isRecurring: false,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    completionStatus: "onTime",
    hasComplaint: true,
    rating: 4,
    reqCategory: "itemRequest",
    items: [
      { itemName: "Towels", quantities: 2, description: "Extra soft" },
      { itemName: "Toiletries", quantities: 1 },
    ],
  },
  {
    id: "192021",
    title: "Repair",
    from: "Room 102",
    to: "Maintenance",
    taskType: "internal",
    status: "completed",
    isRecurring: false,
    scheduledDate: new Date(),
    completionStatus: "delayed",
    hasComplaint: false,
    rating: 3,
    reqCategory: "serviceRequest",
    services: [
      { serviceName: "HVAC" },
      { serviceName: "Carpentry", description: "Urgent" },
    ],
  },
  {
    id: "222324",
    title: "Inspection",
    from: "Quality Control",
    to: "Storage",
    taskType: "internal",
    status: "ongoing",
    isRecurring: true,
    scheduledDate: new Date(),
    acceptanceStatus: "notAccepted",
    hasComplaint: false,
    rating: 5,
  },
  {
    id: "252627",
    title: "Room Setup",
    from: "Reception",
    to: "Room 301",
    taskType: "guest",
    status: "completed",
    isRecurring: false,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    completionStatus: "onTime",
    hasComplaint: false,
    rating: 4,
  },
  {
    id: "282930",
    title: "Checklist",
    from: "Supervisor",
    to: "Floor",
    taskType: "internal",
    status: "ongoing",
    isRecurring: false,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    hasComplaint: false,
    rating: 3,
  },
  {
    id: "313233",
    title: "Inventory",
    from: "Warehouse",
    to: "Store",
    taskType: "internal",
    status: "ongoing",
    isRecurring: true,
    scheduledDate: new Date(),
    acceptanceStatus: "notAccepted",
    hasComplaint: false,
    rating: 5,
  },
  {
    id: "343536",
    title: "Maintenance",
    from: "Facilities",
    to: "Rooms",
    taskType: "internal",
    status: "completed",
    isRecurring: false,
    scheduledDate: new Date(),
    completionStatus: "delayed",
    hasComplaint: true,
    rating: 2,
  },
  {
    id: "373839",
    title: "Room Service",
    from: "Kitchen",
    to: "Room 401",
    taskType: "guest",
    status: "ongoing",
    isRecurring: false,
    scheduledDate: new Date(),
    acceptanceStatus: "notAccepted",
    hasComplaint: false,
    rating: 4,
  },
  {
    id: "404142",
    title: "Supply Restock",
    from: "Storage",
    to: "Store",
    taskType: "internal",
    status: "completed",
    isRecurring: true,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    completionStatus: "onTime",
    hasComplaint: false,
    rating: 5,
    reqCategory: "itemRequest",
    items: [
      { itemName: "Pens", quantities: 50 },
      { itemName: "Paper", quantities: 100 },
    ],
    services: [
      { serviceName: "Delivery" },
      { serviceName: "Restocking", description: "Urgent" },
    ],
  },
  {
    id: "434445",
    title: "Inspection",
    from: "Quality Control",
    to: "Storage",
    taskType: "internal",
    status: "ongoing",
    isRecurring: true,
    scheduledDate: new Date(),
    acceptanceStatus: "notAccepted",
    hasComplaint: false,
    rating: 3,
  },
  {
    id: "464748",
    title: "Repair",
    from: "Room 103",
    to: "Maintenance",
    taskType: "internal",
    status: "completed",
    isRecurring: false,
    scheduledDate: new Date(),
    acceptanceStatus: "accepted",
    completionStatus: "delayed",
    hasComplaint: true,
    rating: 4,
  },
  {
    id: "495051",
    title: "Room Setup",
    from: "Reception",
    to: "Room 302",
    taskType: "guest",
    status: "ongoing",
    isRecurring: false,
    scheduledDate: new Date(),
    acceptanceStatus: "notAccepted",
    completionStatus: "onTime",
    hasComplaint: true,
    rating: 2,
  },
];
